@startuml Order_numberZK2
left to right direction

actor Customer as customer #lightblue

rectangle "Order Number" as order_number {
  (View profile)
  (Select past order)
  (Logout)
}

customer -> order_number: Login
order_number --> customer: True

@enduml
