@startuml SubmitAReview_HS

actor Customer
participant "Website" as website
database "Database" as database

Customer -> website: Login
Customer -> website: View Product
Customer -> website: Write Review
Customer -> website: Submit Review
website -> database: Save Review

@enduml
