@startuml Reset_Password_ZK2

left to right direction
actor Customer

rectangle "Reset Password after logging in" as reset_password1 {
  (Login)
  (View profile)
  (Reset password)
  (Logout)
}

Customer --> (Login)
Customer --> (View profile)
Customer --> (Reset password)
Customer --> (Logout)

rectangle "Reset Password before logging in" as reset_password2 {
  (Forgot password)
  (Enter email for reset)
  (Receive reset link)
  (Reset password)
  (Login)
}

Customer --> (Forgot password)
Customer --> (Enter email for reset)
Customer --> (Receive reset link)
Customer --> (Reset password)
Customer --> (Login)
@enduml
